webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    cache: true

when@dev:
    webpack_encore:
        cache: false

when@test:
    webpack_encore:
        strict_mode: false

when@smoketest:
    webpack_encore:
        strict_mode: false
